<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="resources\clear-filter.png" />
    <None Remove="resources\magnifying-glass.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="resources\clear-filter.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="resources\magnifying-glass.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pra.Freezer.Keeper.Core\Pra.Freezer.Keeper.Core.csproj" />
  </ItemGroup>

</Project>
